# Generated by Django 4.0 on 2021-12-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_recipe_id', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('glass', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='recipes.Ingredient')),
            ],
        ),
    ]
