# Generated by Django 4.0 on 2021-12-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_userrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='user_recipes', to='recipes.Ingredient'),
        ),
    ]
