# Generated by Django 4.0 on 2021-12-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('recipes', '0003_remove_userrecipe_ingredients_userrecipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='profiles',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_recipes', to='accounts.profile'),
        ),
    ]
