# Generated by Django 4.0 on 2021-12-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_profiles_userrecipe_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='profiles',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
