# Generated by Django 4.0 on 2021-12-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipe',
            name='thumbnail',
        ),
    ]
