# Generated by Django 4.0 on 2021-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_userrecipe_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipe',
            name='image',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
